In [20]:
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
# from sklearn.linear_model import LogisticRegression, LinearRegression
# from scipy.special import expit

In [21]:
df = pd.read_stata('/Users/zwanran/Desktop/STAT27420/Final/STAT27420-final-code/Data/data/Comprehensive-Sample.dta')
# prepare for fist part regression
varlist = ['onsetUCS', 'onset2COWCS', 'logvaloilres', 'logGDP_M', 'ecgrowth', 'logpop_M', 'logpopdens', 
           'democracy', 'logmountain', 'ethnic_fractionalization', 'religion_fractionalization', 
           'language_fractionalization', 'leg_british', 'year', 'code3', 'numcode']
varlist_UNDP = 
# cleansing
df = df.dropna(axis = 0, how ='any', subset=varlist_COW)
# df_disc = pd.read_stata('ASPO-Sample.dta')

Plan to replicate Table 2 with ML:
1. Replicate Probit, Pooled OLS, FE OLS on COW dataset
2. Replicate Pooled OLS, FE OLS on UCPD/PRIO dataset
   1. on democratic subsample
   2. on non-democratic subsample

In [22]:
# split dataset by country
df['oilreserves_mean'] = df.groupby(['numcode'])['oilreserves'].transform('mean')
df['nooil'] = (df['oilreserves_mean']==0)
df_nooil = df[df['nooil']==True].copy()

df_oil = df[df['nooil']==False].copy()
df_oil['logvaloilres_mean'] = df_oil.groupby(['numcode'])['logvaloilres'].transform('mean')
logvaloilres_quantile = np.quantile(df_oil['logvaloilres_mean'], [1/3, 2/3])

df_oil['smalloil'] = (df_oil['logvaloilres_mean']<logvaloilres_quantile[0])
df_smalloil = df_oil[df_oil['smalloil']==True].copy()

df_oil['bigoil'] = (df_oil['logvaloilres_mean']>logvaloilres_quantile[1])
df_bigoil = df_oil[df_oil['bigoil']==True].copy()

In [23]:
df

,year,numcode,oilreserves_full,oilreserves,oilreserves_public,newdiscovery_aspo,aspo,wildcat,endowment,pop_maddison,...,dincidence2COW,dmilexpSIPRI,dincidenceU,dcoup,decade,wildcatsample,lowincsample,opec,oilreserves_mean,nooil
81,1930.0,8,0.282660,0.282660,NaN,0.00076,1.0,1.0,0.8,982.000000,...,0.0,NaN,NaN,NaN,1.0,1.0,1.0,0.0,0.211419,False
82,1931.0,8,0.282660,0.282660,NaN,0.00000,1.0,0.0,0.8,988.000000,...,0.0,NaN,NaN,NaN,1.0,NaN,1.0,0.0,0.211419,False
83,1932.0,8,0.282660,0.282660,NaN,0.00000,1.0,0.0,0.8,993.000000,...,0.0,NaN,NaN,NaN,1.0,NaN,1.0,0.0,0.211419,False
84,1933.0,8,0.282649,0.282649,NaN,0.00000,1.0,0.0,0.8,998.000000,...,0.0,NaN,NaN,NaN,1.0,NaN,1.0,0.0,0.211419,False
85,1934.0,8,0.282638,0.282638,NaN,0.00000,1.0,0.0,0.8,1003.000000,...,0.0,NaN,NaN,NaN,1.0,NaN,1.0,0.0,0.211419,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17910,1999.0,894,0.000000,0.000000,0.0,0.00000,NaN,0.0,0.0,9967.447266,...,0.0,NaN,0.0,0.0,7.0,NaN,1.0,0.0,0.000000,True
17911,2000.0,894,0.000000,0.000000,0.0,0.00000,NaN,0.0,0.0,10205.261719,...,0.0,NaN,0.0,0.0,8.0,NaN,1.0,0.0,0.000000,True
17912,2001.0,894,0.000000,0.000000,0.0,0.00000,NaN,0.0,0.0,10439.789062,...,0.0,NaN,0.0,0.0,8.0,NaN,1.0,0.0,0.000000,True
17913,2002.0,894,0.000000,0.000000,0.0,0.00000,NaN,0.0,0.0,10633.077148,...,0.0,NaN,0.0,0.0,8.0,NaN,1.0,0.0,0.000000,True
17914,2003.0,894,0.000000,0.000000,0.0,0.00000,NaN,0.0,0.0,10799.936523,...,0.0,NaN,0.0,0.0,8.0,NaN,1.0,0.0,0.000000,True

In [45]:
# binarize treatment
df.groupby(['numcode'])['log'].



# ---- logistic function ----
## reference: https://scikit-learn.org/stable/auto_examples/linear_model/plot_logistic.html#sphx-glr-auto-examples-linear-model-plot-logistic-py
## treat year and country just as covariates first

array([nan, nan])